Use ttl and max_ttl from the role when renewing a lease
exoscale/vault-plugin-secrets-exoscale pull request #11
Opened 2021-12-10 14:12 UTC by 7fELF

When the plugin renews the lease, it should take the ttl and max_ttl from the configuration of the role (if defined).

2021-12-10 14:45 UTC, exo-cedric approved these changes
Lgtm, afaict. Thx!

2021-12-10 16:54 UTC, falzm commented on secret_apikey.go
> +	roleRaw, ok := req.Secret.InternalData["role"]
`roleName` would be more appropriate, IMO.

2021-12-10 17:14 UTC, falzm requested changes
No objection about this change on the concept (good catch 👍), however please see my inline suggested changes making the implementation more consistent with the rest of the codebase (e.g. with related method `exoscaleBackend.createAPIKey()`).

2021-12-10 17:14 UTC, falzm commented on secret_apikey.go
> +	roleRaw, ok := req.Secret.InternalData["role"]
```suggestion
	roleName, ok := req.Secret.InternalData["role"]
```

2021-12-10 17:14 UTC, falzm commented on secret_apikey.go
> +
```suggestion
	role, err := b.roleConfig(ctx, req.Storage, roleName.(string))
	if err != nil {
		return nil, fmt.Errorf("error retrieving role: %w", err)
	}
	if role == nil {
		return logical.ErrorResponse(fmt.Sprintf("role %q not found", roleName)), nil
	}

```

2021-12-10 17:14 UTC, falzm commented on secret_apikey.go
> +		lc = roleEntry.LeaseConfig
```suggestion
		lc = role.LeaseConfig
```

2021-12-13 14:49 UTC, falzm approved these changes

2021-12-13 14:50 UTC, merged